const express = require('express');
const { authenticate, authorize } = require('../middleware/auth');
const { createBooking, myBookings, getBooking, cancelBooking, adminBookings, updateBooking, plumberBookings, plumberUpdateBooking } = require('../controllers/bookings');
const router = express.Router();
router.post('/', authenticate, authorize('customer'), createBooking);
router.get('/my', authenticate, authorize('customer'), myBookings);
router.get('/plumber', authenticate, authorize('plumber'), plumberBookings);
router.get('/admin/all', authenticate, authorize('admin'), adminBookings);
router.get('/:id', authenticate, getBooking);
router.patch('/:id/cancel', authenticate, authorize('customer'), cancelBooking);
router.patch('/:id/admin', authenticate, authorize('admin'), updateBooking);
router.patch('/:id/plumber', authenticate, authorize('plumber'), plumberUpdateBooking);
module.exports = router;
