const express = require('express');
const { authenticate, authorize } = require('../middleware/auth');
const { photoUpload } = require('../middleware/upload');
const { searchPlumbers, getPublicProfile, getMyProfile, updateMyProfile, uploadProfilePhoto, publicStats } = require('../controllers/plumbers');
const router = express.Router();
router.get('/search', searchPlumbers);
router.get('/stats', publicStats);
router.get('/me', authenticate, authorize('plumber'), getMyProfile);
router.patch('/me', authenticate, authorize('plumber'), updateMyProfile);
router.post('/me/photo', authenticate, authorize('plumber'), photoUpload.single('photo'), uploadProfilePhoto);
router.get('/:id', getPublicProfile);
module.exports = router;
