import React, { useEffect, useMemo, useState } from 'react';
import '../styles/AdminDashboard.css';
import { getAdminBookings, updateAdminBooking } from '../api/bookingApi';
import { getAdminStats, getMessages, getPlumbers, getUsers, setUserStatus, verifyPlumber, updateMessage, createPlumber } from '../api/adminApi';
import { getAllServices, createService, updateService, deleteService } from '../api/serviceApi';
import ServiceIcon from '../components/ServiceIcon';
import Icon from '../components/Icon';
import Stars from '../components/Stars';
import { useAutoRefresh } from '../hooks/useAutoRefresh';

const tabs=[['overview','Overview'],['bookings','Bookings'],['users','Users'],['plumbers','Plumbers'],['services','Services'],['messages','Messages']];
const statuses=['pending','assigned','confirmed','on_the_way','arrived','in_progress','completed','reviewed','cancelled','rejected','expired'];
function AdminDashboard(){
 const [tab,setTab]=useState('overview'),[stats,setStats]=useState({}),[bookings,setBookings]=useState([]),[users,setUsers]=useState([]),[plumbers,setPlumbers]=useState([]),[services,setServices]=useState([]),[messages,setMessages]=useState([]),[query,setQuery]=useState(''),[loading,setLoading]=useState(true),[error,setError]=useState(''),[serviceForm,setServiceForm]=useState({name:'',description:'',price:'',icon:''}),[editingService,setEditingService]=useState(null);
 const load=async(opts={})=>{if(!opts.silent)setLoading(true);setError('');try{const [s,b,u,p,sv,m]=await Promise.all([getAdminStats(),getAdminBookings(),getUsers(),getPlumbers(),getAllServices(),getMessages()]);setStats(s.stats||{});setBookings(b.bookings||[]);setUsers(u.users||[]);setPlumbers(p.plumbers||[]);setServices(sv.services||[]);setMessages(m.messages||[])}catch(e){if(!opts.silent)setError(e.message)}finally{if(!opts.silent)setLoading(false)}};useEffect(()=>{load()},[]);
 useAutoRefresh(()=>load({silent:true}),25000);
 const filteredUsers=useMemo(()=>users.filter(u=>`${u.name} ${u.email} ${u.phone||''} ${u.role} ${u.status}`.toLowerCase().includes(query.toLowerCase())),[users,query]);const filteredBookings=useMemo(()=>bookings.filter(b=>`${b.customer_name} ${b.customer_email||''} ${b.service_name} ${b.status} ${b.address}`.toLowerCase().includes(query.toLowerCase())),[bookings,query]);const filteredPlumbers=useMemo(()=>plumbers.filter(p=>`${p.name} ${p.email} ${p.phone||''} ${p.profession||''} ${p.location_name||''} ${p.verified?'verified':'pending'}`.toLowerCase().includes(query.toLowerCase())),[plumbers,query]);const filteredMessages=useMemo(()=>messages.filter(m=>`${m.name} ${m.email} ${m.subject} ${m.status}`.toLowerCase().includes(query.toLowerCase())),[messages,query]);
 const status=async(id,value,plumberId)=>{try{await updateAdminBooking(id,{status:value,plumber_id:plumberId||null});load()}catch(e){setError(e.message)}};const toggleUser=async(id,current)=>{try{await setUserStatus(id,current==='active'?'suspended':'active');load()}catch(e){setError(e.message)}};const verify=async(id,value)=>{try{await verifyPlumber(id,value);load()}catch(e){setError(e.message)}};const changeMessage=async(id,v)=>{try{await updateMessage(id,v);load()}catch(e){setError(e.message)}};
 const saveService=async e=>{e.preventDefault();try{if(editingService)await updateService(editingService.id,serviceForm);else await createService(serviceForm);setEditingService(null);setServiceForm({name:'',description:'',price:'',icon:''});load()}catch(e){setError(e.message)}};
 const title=tabs.find(x=>x[0]===tab)?.[1]||'Overview';const newMessages=messages.filter(m=>m.status==='new').length;
 return <div className="admin-container"><aside className="sidebar"><div className="admin-brand"><div className="admin-logo-surface"><img src="/plumbpro-mark.svg" alt="PlumbPro logo"/></div><div><strong>Admin Console</strong><span>Operations workspace</span></div></div><nav>{tabs.map(([key,label])=><button key={key} className={tab===key?'active':''} onClick={()=>{setTab(key);setQuery('')}}><span className={`admin-nav-icon icon-${key}`}></span>{label}{key==='messages'&&newMessages>0?<em>{newMessages}</em>:null}</button>)}</nav><div className="sidebar-foot"><p>Manage live users, bookings, plumbers, services and support messages.</p><button onClick={()=>load()}><Icon name="refresh" size={14}/> Refresh data</button></div></aside>
 <main className="admin-main"><header className="admin-top"><div><span className="eyebrow">ADMINISTRATION</span><h1>{title}</h1><p>One workspace for the real data connected to your MySQL database.</p></div><div className="admin-tools">{tab!=='overview'&&<div className="admin-search"><Icon name="search" size={15}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder={`Search ${title.toLowerCase()}…`}/>{query&&<button onClick={()=>setQuery('')}>×</button>}</div>}<button className="refresh-btn" onClick={()=>load()} disabled={loading}><Icon name="refresh" size={14}/> {loading?'Refreshing…':'Refresh'}</button></div></header>{error&&<div className="form-error">{error}</div>}{loading?<div className="admin-loading"><span></span>Loading live data…</div>:<>
 {tab==='overview'&&<Overview stats={stats} bookings={bookings.slice(0,8)} plumbers={plumbers} onStatus={status} onNavigate={setTab}/>} 
 {tab==='bookings'&&<Panel title="Bookings" text={`${filteredBookings.length} matching booking${filteredBookings.length===1?'':'s'}.`}><BookingTable bookings={filteredBookings} plumbers={plumbers} onStatus={status}/></Panel>}
 {tab==='users'&&<Panel title="User accounts" text="Search by Gmail, name, phone, role or status. Email cells stay readable and can be copied or opened directly."><div className="table-wrap admin-table"><table><thead><tr><th>User</th><th>Email</th><th>Role</th><th>Phone</th><th>Status</th><th>Created</th><th>Action</th></tr></thead><tbody>{filteredUsers.length?filteredUsers.map(u=><tr key={u.id}><td><div className="person-cell"><span>{(u.name||'?').charAt(0).toUpperCase()}</span><strong>{u.name}</strong></div></td><td><div className="email-cell"><a href={`mailto:${u.email}`} title={u.email}>{u.email}</a><button onClick={()=>navigator.clipboard?.writeText(u.email)}>Copy</button></div></td><td><span className="role-chip">{u.role}</span></td><td>{u.phone||'—'}</td><td><span className={`status status-${u.status}`}>{u.status}</span></td><td>{new Date(u.created_at).toLocaleDateString()}</td><td>{u.role!=='admin'&&<button className="table-btn" onClick={()=>toggleUser(u.id,u.status)}>{u.status==='active'?'Suspend':'Activate'}</button>}</td></tr>):<Empty cols={7}/>}</tbody></table></div></Panel>}
 {tab==='plumbers'&&<><Panel title="Plumber verification" text="Review professional details and decide which real plumber profiles can appear in public search."><div className="table-wrap admin-table"><table><thead><tr><th>Plumber</th><th>Professional</th><th>Location</th><th>Experience</th><th>Rating</th><th>Availability</th><th>Verification</th></tr></thead><tbody>{filteredPlumbers.length?filteredPlumbers.map(p=><tr key={p.id}><td><div className="person-cell"><span>{p.name?.charAt(0)||'P'}</span><strong>{p.name}</strong></div><small className="subline">{p.email}</small></td><td>{p.profession||'—'}<small className="subline">{p.work_mode==='team'?'Team':'Solo'} · {p.education||'Training not listed'}</small></td><td>{p.location_name||'—'}<small className="subline">{p.can_travel?'Can travel':'Local only'}</small></td><td>{Number(p.experience_years||0)} yrs</td><td><Stars rating={p.rating} count={p.review_count}/></td><td><span className={`status ${p.available?'status-active':'status-suspended'}`}>{p.available?'Available':'Unavailable'}</span></td><td><button className={`table-btn ${p.verified?'danger':''}`} onClick={()=>verify(p.id,!p.verified)}>{p.verified?'Remove verification':'Verify plumber'}</button></td></tr>):<Empty cols={7}/>}</tbody></table></div></Panel><Panel title="Create plumber account" text="Admins can create a plumber login for professionals who prefer to be onboarded directly."><PlumberCreate onCreated={load}/></Panel></>}
 {tab==='services'&&<><Panel title={editingService?'Edit service':'Add service'} text="This catalog powers the public Services section. Only active services are shown to customers."><form className="admin-form-grid" onSubmit={saveService}><input placeholder="Service name" value={serviceForm.name} onChange={e=>setServiceForm({...serviceForm,name:e.target.value})} required/><input type="number" min="0" placeholder="Price (NPR)" value={serviceForm.price} onChange={e=>setServiceForm({...serviceForm,price:e.target.value})}/><input className="wide-field" placeholder="Description" value={serviceForm.description} onChange={e=>setServiceForm({...serviceForm,description:e.target.value})} required/><button className="primary-action">{editingService?'Save changes':'Add service'}</button>{editingService&&<button type="button" className="secondary-action" onClick={()=>{setEditingService(null);setServiceForm({name:'',description:'',price:'',icon:''})}}>Cancel</button>}</form></Panel><Panel title="Service catalog" text={`${services.length} configured services.`}><div className="table-wrap admin-table"><table><thead><tr><th>Service</th><th>Description</th><th>Price</th><th>Status</th><th>Actions</th></tr></thead><tbody>{services.length?services.map(s=><tr key={s.id}><td><div className="service-cell"><ServiceIcon name={s.name} size={17}/><strong>{s.name}</strong></div></td><td className="description-cell">{s.description}</td><td>NPR {Number(s.price||0).toLocaleString()}</td><td><span className={`status status-${s.status}`}>{s.status}</span></td><td><button className="table-btn" onClick={()=>{setEditingService(s);setServiceForm({name:s.name,description:s.description||'',price:s.price||'',icon:s.icon||''});window.scrollTo({top:0,behavior:'smooth'})}}>Edit</button>{s.status==='active'&&<button className="table-btn danger" onClick={async()=>{if(window.confirm('Disable this service?')){await deleteService(s.id);load()}}}>Disable</button>}</td></tr>):<Empty cols={5}/>}</tbody></table></div></Panel></>}
 {tab==='messages'&&<Panel title="Contact inbox" text="Every contact form submission is stored here. Work through messages and update their status as you handle them."><div className="table-wrap admin-table"><table><thead><tr><th>Sender</th><th>Email</th><th>Subject</th><th>Message</th><th>Status</th><th>Received</th><th>Action</th></tr></thead><tbody>{filteredMessages.length?filteredMessages.map(m=><tr key={m.id}><td><strong>{m.name}</strong></td><td><div className="email-cell"><a href={`mailto:${m.email}`}>{m.email}</a></div></td><td>{m.subject}</td><td className="message-preview" title={m.message}>{m.message}</td><td><span className={`status status-${m.status}`}>{m.status}</span></td><td>{new Date(m.created_at).toLocaleString()}</td><td><select value={m.status} onChange={e=>changeMessage(m.id,e.target.value)}><option value="new">New</option><option value="read">Read</option><option value="replied">Replied</option></select></td></tr>):<Empty cols={7}/>}</tbody></table></div></Panel>}
 </>}</main></div>
}
function Panel({title,text,children}){return <section className="admin-panel"><div className="panel-heading"><div><h2>{title}</h2><p>{text}</p></div></div>{children}</section>}
function Empty({cols}){return <tr><td colSpan={cols}><div className="empty-state">No records found.</div></td></tr>}
function Overview({stats,bookings,plumbers,onStatus,onNavigate}){return <><div className="stat-grid"><Stat label="Customers" value={stats.customers||0}/><Stat label="Plumbers" value={stats.plumbers||0}/><Stat label="Verified plumbers" value={stats.verified_plumbers||0}/><Stat label="Bookings" value={stats.bookings||0}/><Stat label="Pending" value={stats.pending||0}/><Stat label="Active jobs" value={stats.active||0}/><Stat label="Completed" value={stats.completed||0}/><Stat label="New messages" value={stats.new_messages||0}/></div><div className="overview-grid"><Panel title="Recent bookings" text="Latest live booking activity."><BookingTable bookings={bookings} plumbers={plumbers} onStatus={onStatus}/><button className="panel-link" onClick={()=>onNavigate('bookings')}>View all bookings →</button></Panel><Panel title="Quick actions" text="Jump directly to the most common admin tasks."><div className="quick-actions"><button onClick={()=>onNavigate('users')}><b>Users</b><span>Manage customer and plumber accounts</span>→</button><button onClick={()=>onNavigate('plumbers')}><b>Plumbers</b><span>Review and verify professional profiles</span>→</button><button onClick={()=>onNavigate('bookings')}><b>Bookings</b><span>Assign plumbers and update progress</span>→</button><button onClick={()=>onNavigate('messages')}><b>Messages</b><span>Handle website contact submissions</span>→</button></div></Panel></div></>}
function Stat({label,value}){return <div className="stat-card"><span>{label}</span><strong>{value}</strong></div>}
function BookingTable({bookings,plumbers,onStatus}){return <div className="table-wrap admin-table"><table><thead><tr><th>Customer</th><th>Service</th><th>Date</th><th>Status</th><th>Plumber</th></tr></thead><tbody>{bookings.length?bookings.map(b=><tr key={b.id}><td><div className="customer-booking"><strong>{b.customer_name}</strong><small>{b.customer_email||'No email'}</small></div></td><td>{b.service_name}</td><td>{new Date(b.booking_date).toLocaleDateString()}<small className="subline">{String(b.booking_time).slice(0,5)}</small></td><td><select className="status-select" value={b.status} onChange={e=>onStatus(b.id,e.target.value,b.plumber_id)}>{statuses.map(s=><option key={s} value={s}>{s.replace('_',' ')}</option>)}</select></td><td><select className="assignment-select" value={b.plumber_id||''} onChange={e=>{const id=Number(e.target.value);if(id)onStatus(b.id,'assigned',id)}}><option value="">{b.plumber_name||'Assign plumber'}</option>{plumbers.filter(p=>p.status==='active'&&p.verified).map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></td></tr>):<Empty cols={5}/>}</tbody></table></div>}
function PlumberCreate({onCreated}){const [form,setForm]=useState({name:'',email:'',phone:'',password:'',profession:'',location_name:''});const [busy,setBusy]=useState(false);const [error,setError]=useState('');const save=async e=>{e.preventDefault();setBusy(true);setError('');try{await createPlumber(form);setForm({name:'',email:'',phone:'',password:'',profession:'',location_name:''});onCreated()}catch(err){setError(err.message)}finally{setBusy(false)}};return <><form className="admin-form-grid" onSubmit={save}><input placeholder="Full name" value={form.name} onChange={e=>setForm({...form,name:e.target.value})} required/><input type="email" placeholder="Email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})} required/><input placeholder="Phone" value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})}/><input type="password" minLength="6" placeholder="Temporary password" value={form.password} onChange={e=>setForm({...form,password:e.target.value})} required/><input placeholder="Profession" value={form.profession} onChange={e=>setForm({...form,profession:e.target.value})} required/><input placeholder="Service area" value={form.location_name} onChange={e=>setForm({...form,location_name:e.target.value})} required/><button className="primary-action" disabled={busy}>{busy?'Creating…':'Create plumber'}</button></form>{error&&<div className="form-error">{error}</div>}</>}
export default AdminDashboard;
