import React, { useEffect, useMemo, useState } from 'react';
import { Link, useNavigate } from 'react-router-dom';
import '../styles/AdminDashboard.css';
import { getAdminBookings, updateAdminBooking } from '../api/bookingApi';
import { getAdminStats, getMessages, getPlumbers, getUsers, setUserStatus, verifyPlumber, updateMessage, createPlumber, getAnalytics } from '../api/adminApi';
import { getAllServices, createService, updateService, deleteService } from '../api/serviceApi';
import { getReports, updateReport, REPORT_REASONS } from '../api/reportApi';
import { getAllFeedback, updateFeedbackStatus } from '../api/feedbackApi';
import ServiceIcon from '../components/ServiceIcon';
import Icon from '../components/Icon';
import Stars from '../components/Stars';
import NotificationBell from '../components/NotificationBell';
import { useAutoRefresh } from '../hooks/useAutoRefresh';
import { useConfirm } from '../context/ConfirmContext';
import { useAuth } from '../context/AuthContext';
import { useTheme } from '../context/ThemeContext';
import DashboardWatermark from '../components/DashboardWatermark';

const tabs=[['overview','Overview'],['bookings','Bookings'],['users','Users'],['plumbers','Plumbers'],['services','Services'],['support','Support'],['feedback','Feedback'],['analytics','Analytics']];
const tabIcons={overview:'dashboard',bookings:'bookings',users:'users',plumbers:'briefcase',services:'wrench',support:'shield',feedback:'star',analytics:'chart'};
const statuses=['pending','assigned','confirmed','on_the_way','arrived','in_progress','completed','reviewed','cancelled','rejected','expired'];
const reasonLabel=r=>REPORT_REASONS.find(x=>x.value===r)?.label||r;

function AdminDashboard(){
 const confirm=useConfirm();
 const {user,logout}=useAuth();
 const {isDark,toggleTheme}=useTheme();
 const navigate=useNavigate();
 const handleLogout=()=>{logout();navigate('/')};
 const [tab,setTab]=useState('overview'),[stats,setStats]=useState({}),[bookings,setBookings]=useState([]),[users,setUsers]=useState([]),[plumbers,setPlumbers]=useState([]),[services,setServices]=useState([]),[messages,setMessages]=useState([]),[reports,setReports]=useState([]),[feedback,setFeedback]=useState([]),[analyticsData,setAnalyticsData]=useState(null),[analyticsRange,setAnalyticsRange]=useState(30),[query,setQuery]=useState(''),[loading,setLoading]=useState(true),[error,setError]=useState(''),[serviceForm,setServiceForm]=useState({name:'',description:'',price:'',is_negotiable:false,icon:''}),[editingService,setEditingService]=useState(null),[userRole,setUserRole]=useState('all');
 const load=async(opts={})=>{if(!opts.silent)setLoading(true);setError('');try{const [s,b,u,p,sv,m,r,a,f]=await Promise.all([getAdminStats(),getAdminBookings(),getUsers(),getPlumbers(),getAllServices(),getMessages(),getReports(),getAnalytics(analyticsRange),getAllFeedback()]);setStats(s.stats||{});setBookings(b.bookings||[]);setUsers(u.users||[]);setPlumbers(p.plumbers||[]);setServices(sv.services||[]);setMessages(m.messages||[]);setReports(r.reports||[]);setAnalyticsData(a);setFeedback(f.feedback||[])}catch(e){if(!opts.silent)setError(e.message)}finally{if(!opts.silent)setLoading(false)}};useEffect(()=>{load()},[analyticsRange]);
 const changeFeedback=async(id,status)=>{try{await updateFeedbackStatus(id,status);load()}catch(e){setError(e.message)}};
 useAutoRefresh(()=>load({silent:true}),40000);
 const usersByRole=useMemo(()=>({all:users,admin:users.filter(u=>u.role==='admin'),plumber:users.filter(u=>u.role==='plumber'),customer:users.filter(u=>u.role==='customer')}),[users]);
 const filteredUsers=useMemo(()=>usersByRole[userRole].filter(u=>`${u.name} ${u.email} ${u.phone||''} ${u.role} ${u.status}`.toLowerCase().includes(query.toLowerCase())),[usersByRole,userRole,query]);const filteredBookings=useMemo(()=>bookings.filter(b=>`${b.customer_name} ${b.customer_email||''} ${b.service_name} ${b.status} ${b.address}`.toLowerCase().includes(query.toLowerCase())),[bookings,query]);const filteredPlumbers=useMemo(()=>plumbers.filter(p=>`${p.name} ${p.email} ${p.phone||''} ${p.profession||''} ${p.location_name||''} ${p.verified?'verified':'pending'}`.toLowerCase().includes(query.toLowerCase())),[plumbers,query]);const filteredMessages=useMemo(()=>messages.filter(m=>`${m.name} ${m.email} ${m.subject} ${m.status}`.toLowerCase().includes(query.toLowerCase())),[messages,query]);const filteredReports=useMemo(()=>reports.filter(r=>`${r.reporter_name} ${r.plumber_name} ${reasonLabel(r.reason)} ${r.status}`.toLowerCase().includes(query.toLowerCase())),[reports,query]);const filteredFeedback=useMemo(()=>feedback.filter(f=>`${f.user_name} ${f.role} ${f.comment||''} ${f.status}`.toLowerCase().includes(query.toLowerCase())),[feedback,query]);
 const status=async(id,value,plumberId)=>{try{await updateAdminBooking(id,{status:value,plumber_id:plumberId||null});load()}catch(e){setError(e.message)}};
 const toggleUser=async(id,current)=>{const suspending=current==='active';if(suspending&&!(await confirm({title:'Suspend this account?',message:'They will not be able to log in until you reactivate the account. This does not delete any of their data.',confirmLabel:'Suspend account'})))return;try{await setUserStatus(id,suspending?'suspended':'active');load()}catch(e){setError(e.message)}};
 const verify=async(id,value)=>{if(!value&&!(await confirm({title:'Remove verification?',message:"This plumber will be hidden from public search results until they're re-verified.",confirmLabel:'Remove verification'})))return;try{await verifyPlumber(id,value);load()}catch(e){setError(e.message)}};
 const changeMessage=async(id,v)=>{if(v==='archived'&&!(await confirm({title:'Archive this message?',message:"It will be moved out of the active inbox. You can still find it, but it won't show in the default list.",confirmLabel:'Archive message'})))return;try{await updateMessage(id,v);load()}catch(e){setError(e.message)}};
 const changeReport=async(id,v,note)=>{try{await updateReport(id,v,note);load()}catch(e){setError(e.message)}};
 const saveService=async e=>{e.preventDefault();try{if(editingService)await updateService(editingService.id,serviceForm);else await createService(serviceForm);setEditingService(null);setServiceForm({name:'',description:'',price:'',is_negotiable:false,icon:''});load()}catch(e){setError(e.message)}};
 const removeService=async(s)=>{if(!(await confirm({title:`Disable "${s.name}"?`,message:'Customers will no longer be able to book this service. You can re-enable it later by editing it.',confirmLabel:'Disable service'})))return;try{await deleteService(s.id);load()}catch(e){setError(e.message)}};
 const title=tabs.find(x=>x[0]===tab)?.[1]||'Overview';const newMessages=messages.filter(m=>m.status==='new').length;const openReports=reports.filter(r=>r.status==='new').length;const supportBadge=newMessages+openReports;const pendingFeedback=feedback.filter(f=>f.status==='pending').length;
 return <div className="admin-container"><aside className="sidebar"><div className="admin-brand"><div className="admin-logo-surface"><img src="/plumbpro-mark.svg" alt="PlumbPro logo"/></div><div><strong>Admin Console</strong><span>Operations workspace</span></div></div><nav>{tabs.map(([key,label])=><button key={key} className={tab===key?'active':''} onClick={()=>{setTab(key);setQuery('');setUserRole('all')}}><Icon name={tabIcons[key]} size={16}/>{label}{key==='support'&&supportBadge>0?<em>{supportBadge}</em>:null}{key==='feedback'&&pendingFeedback>0?<em>{pendingFeedback}</em>:null}</button>)}</nav><div className="sidebar-foot"><div className="sidebar-account"><div className="sidebar-account-chip">{(user?.name||'A').charAt(0).toUpperCase()}</div><div><strong>{user?.name}</strong><span>{user?.email}</span></div><NotificationBell/></div><div className="sidebar-icon-row"><button onClick={toggleTheme} title={isDark?'Light mode':'Dark mode'}><Icon name={isDark?'sun':'moon'} size={14}/></button><button onClick={()=>load()} title="Refresh data"><Icon name="refresh" size={14}/></button></div><Link to="/" className="sidebar-back-link"><Icon name="chevronRight" size={13} className="flip"/> Back to website</Link><button className="sidebar-logout" onClick={handleLogout}><Icon name="logout" size={14}/> Logout</button></div></aside>
 <main className="admin-main"><header className="admin-top"><div><span className="eyebrow">ADMINISTRATION</span><h1>{title}</h1><p>One workspace for the real data connected to your MySQL database.</p></div><div className="admin-tools">{tab!=='overview'&&<div className="admin-search"><Icon name="search" size={15}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder={`Search ${title.toLowerCase()}…`}/>{query&&<button onClick={()=>setQuery('')}>×</button>}</div>}<button className="refresh-btn" onClick={()=>load()} disabled={loading}><Icon name="refresh" size={14}/> {loading?'Refreshing…':'Refresh'}</button></div></header>{error&&<div className="form-error">{error}</div>}{loading?<div className="admin-loading"><span></span>Loading live data…</div>:<>
 {tab==='overview'&&<Overview stats={stats} bookings={bookings.slice(0,8)} plumbers={plumbers} onStatus={status} onNavigate={setTab}/>}
 {tab==='bookings'&&<Panel title="Bookings" text={`${filteredBookings.length} matching booking${filteredBookings.length===1?'':'s'}.`}><BookingTable bookings={filteredBookings} plumbers={plumbers} onStatus={status}/></Panel>}
 {tab==='users'&&<Panel title="User accounts" text="Browse by account type, or search by Gmail, name, phone, role or status. Email cells stay readable and can be copied or opened directly."><div className="role-filter-pills">{[['all','All accounts'],['admin','Admins'],['plumber','Plumbers'],['customer','Customers']].map(([key,label])=><button key={key} className={userRole===key?'active':''} onClick={()=>setUserRole(key)}>{label}<em>{usersByRole[key].length}</em></button>)}</div><div className="table-wrap admin-table"><table><thead><tr><th>User</th><th>Email</th><th>Role</th><th>Phone</th><th>Status</th><th>Created</th><th>Action</th></tr></thead><tbody>{filteredUsers.length?filteredUsers.map(u=><tr key={u.id}><td><div className="person-cell"><span>{(u.name||'?').charAt(0).toUpperCase()}</span><strong>{u.name}</strong></div></td><td><div className="email-cell"><a href={`mailto:${u.email}`} title={u.email}>{u.email}</a><button onClick={()=>navigator.clipboard?.writeText(u.email)}>Copy</button></div></td><td><span className="role-chip">{u.role}</span></td><td>{u.phone||'—'}</td><td><span className={`status status-${u.status}`}>{u.status}</span></td><td>{new Date(u.created_at).toLocaleDateString()}</td><td>{u.role!=='admin'&&<button className="table-btn" onClick={()=>toggleUser(u.id,u.status)}>{u.status==='active'?'Suspend':'Activate'}</button>}</td></tr>):<Empty cols={7}/>}</tbody></table></div></Panel>}
 {tab==='plumbers'&&<><Panel title="Plumber verification" text="Review professional details and decide which real plumber profiles get the verified badge. Unverified plumbers still appear in search — verification is a trust signal, not a visibility gate."><div className="table-wrap admin-table"><table><thead><tr><th>Plumber</th><th>Professional</th><th>Location</th><th>Experience</th><th>Rating</th><th>Availability</th><th>Verification</th></tr></thead><tbody>{filteredPlumbers.length?filteredPlumbers.map(p=><tr key={p.id}><td><div className="person-cell"><span>{p.name?.charAt(0)||'P'}</span><strong>{p.name}</strong></div><small className="subline">{p.email}</small></td><td>{p.profession||'—'}<small className="subline">{p.work_mode==='team'?'Team':'Solo'} · {p.education||'Training not listed'}</small></td><td>{p.location_name||'—'}<small className="subline">{p.can_travel?'Can travel':'Local only'}</small></td><td>{Number(p.experience_years||0)} yrs</td><td><Stars rating={p.rating} count={p.review_count}/></td><td><span className={`status ${p.available?'status-active':'status-suspended'}`}>{p.available?'Available':'Unavailable'}</span></td><td><button className={`table-btn ${p.verified?'danger':''}`} onClick={()=>verify(p.id,!p.verified)}>{p.verified?'Remove verification':'Verify plumber'}</button></td></tr>):<Empty cols={7}/>}</tbody></table></div></Panel><Panel title="Create plumber account" text="Admins can create a plumber login for professionals who prefer to be onboarded directly."><PlumberCreate onCreated={load}/></Panel></>}
 {tab==='services'&&<><Panel title={editingService?'Edit service':'Add service'} text="This catalog powers the public Services section. Mark a service negotiable to show 'Negotiable at the job' instead of a fixed number."><form className="admin-form-grid" onSubmit={saveService}><input placeholder="Service name" value={serviceForm.name} onChange={e=>setServiceForm({...serviceForm,name:e.target.value})} required/><input type="number" min="0" placeholder="Price (NPR)" value={serviceForm.price} disabled={serviceForm.is_negotiable} onChange={e=>setServiceForm({...serviceForm,price:e.target.value})}/><label className="negotiable-toggle"><input type="checkbox" checked={serviceForm.is_negotiable} onChange={e=>setServiceForm({...serviceForm,is_negotiable:e.target.checked})}/> Negotiable — price agreed at the job, no fixed number</label><input className="wide-field" placeholder="Description" value={serviceForm.description} onChange={e=>setServiceForm({...serviceForm,description:e.target.value})} required/><button className="primary-action">{editingService?'Save changes':'Add service'}</button>{editingService&&<button type="button" className="secondary-action" onClick={()=>{setEditingService(null);setServiceForm({name:'',description:'',price:'',is_negotiable:false,icon:''})}}>Cancel</button>}</form></Panel><Panel title="Service catalog" text={`${services.length} configured services.`}><div className="table-wrap admin-table"><table><thead><tr><th>Service</th><th>Description</th><th>Price</th><th>Status</th><th>Actions</th></tr></thead><tbody>{services.length?services.map(s=><tr key={s.id}><td><div className="service-cell"><ServiceIcon name={s.name} size={17}/><strong>{s.name}</strong></div></td><td className="description-cell">{s.description}</td><td>{s.is_negotiable?<span className="negotiable-pill">Negotiable at the job</span>:`NPR ${Number(s.price||0).toLocaleString()}`}</td><td><span className={`status status-${s.status}`}>{s.status}</span></td><td><button className="table-btn" onClick={()=>{setEditingService(s);setServiceForm({name:s.name,description:s.description||'',price:s.price||'',is_negotiable:!!s.is_negotiable,icon:s.icon||''});window.scrollTo({top:0,behavior:'smooth'})}}>Edit</button>{s.status==='active'&&<button className="table-btn danger" onClick={()=>removeService(s)}>Disable</button>}</td></tr>):<Empty cols={5}/>}</tbody></table></div></Panel></>}
 {tab==='support'&&<><Panel title="Plumber reports" text="Reports submitted by customers about a specific plumber. Investigate before taking action — you can suspend the plumber's account from the Plumbers or Users tab."><div className="table-wrap admin-table"><table><thead><tr><th>Reported plumber</th><th>Reported by</th><th>Reason</th><th>Details</th><th>Status</th><th>Received</th><th>Action</th></tr></thead><tbody>{filteredReports.length?filteredReports.map(r=><tr key={r.id}><td><strong>{r.plumber_name}</strong><small className="subline">{r.plumber_email}</small></td><td>{r.reporter_name}<small className="subline">{r.reporter_email}</small></td><td><span className="status status-pending">{reasonLabel(r.reason)}</span></td><td className="message-preview" title={r.description}>{r.description||'—'}</td><td><span className={`status status-${r.status==='new'?'pending':r.status==='investigating'?'confirmed':r.status==='resolved'?'completed':'cancelled'}`}>{r.status}</span></td><td>{new Date(r.created_at).toLocaleString()}</td><td><ReportResolver report={r} onChange={changeReport}/></td></tr>):<Empty cols={7}/>}</tbody></table></div></Panel><Panel title="Contact inbox" text="Every contact form submission is stored here. Work through messages and update their status as you handle them."><div className="table-wrap admin-table"><table><thead><tr><th>Sender</th><th>Email</th><th>Subject</th><th>Message</th><th>Status</th><th>Received</th><th>Action</th></tr></thead><tbody>{filteredMessages.length?filteredMessages.map(m=><tr key={m.id}><td><strong>{m.name}</strong></td><td><div className="email-cell"><a href={`mailto:${m.email}`}>{m.email}</a></div></td><td>{m.subject}</td><td className="message-preview" title={m.message}>{m.message}</td><td><span className={`status status-${m.status}`}>{m.status}</span></td><td>{new Date(m.created_at).toLocaleString()}</td><td><select value={m.status} onChange={e=>changeMessage(m.id,e.target.value)}><option value="new">New</option><option value="read">Read</option><option value="resolved">Resolved</option><option value="archived">Archived</option></select></td></tr>):<Empty cols={7}/>}</tbody></table></div></Panel></>}
 {tab==='feedback'&&<Panel title="Platform feedback" text={`Feedback customers and plumbers leave about PlumbPro itself. Approve the ones worth featuring — they'll appear in "What customers say" on the homepage.`}><div className="table-wrap admin-table"><table><thead><tr><th>From</th><th>Role</th><th>Rating</th><th>Comment</th><th>Status</th><th>Received</th><th>Action</th></tr></thead><tbody>{filteredFeedback.length?filteredFeedback.map(f=><tr key={f.id}><td><strong>{f.user_name}</strong></td><td><span className="role-chip">{f.role}</span></td><td><Stars rating={f.rating} count={1} showCount={false}/></td><td className="message-preview" title={f.comment}>{f.comment||'—'}</td><td><span className={`status status-${f.status==='pending'?'pending':f.status==='approved'?'completed':'cancelled'}`}>{f.status}</span></td><td>{new Date(f.created_at).toLocaleString()}</td><td><select value={f.status} onChange={e=>changeFeedback(f.id,e.target.value)}><option value="pending">Pending</option><option value="approved">Approved — show on homepage</option><option value="rejected">Rejected</option></select></td></tr>):<Empty cols={7}/>}</tbody></table></div></Panel>}
 {tab==='analytics'&&<Analytics data={analyticsData} range={analyticsRange} onRangeChange={setAnalyticsRange}/>}
 </>}<DashboardWatermark/></main></div>
}
function Panel({title,text,children}){return <section className="admin-panel"><div className="panel-heading"><div><h2>{title}</h2><p>{text}</p></div></div>{children}</section>}
function Empty({cols}){return <tr><td colSpan={cols}><div className="empty-state">No records found.</div></td></tr>}
function Overview({stats,bookings,plumbers,onStatus,onNavigate}){return <><div className="stat-grid"><Stat label="Customers" value={stats.customers||0} icon="users" tone="blue"/><Stat label="Plumbers" value={stats.plumbers||0} icon="briefcase" tone="accent"/><Stat label="Verified plumbers" value={stats.verified_plumbers||0} icon="shieldCheck" tone="green"/><Stat label="Bookings" value={stats.bookings||0} icon="bookings" tone="primary"/><Stat label="Pending" value={stats.pending||0} icon="clock" tone="amber"/><Stat label="Active jobs" value={stats.active||0} icon="bolt" tone="purple"/><Stat label="Completed" value={stats.completed||0} icon="check" tone="green"/><Stat label="New messages" value={stats.new_messages||0} icon="message" tone="blue"/></div><div className="overview-grid"><Panel title="Recent bookings" text="Latest live booking activity."><BookingTable bookings={bookings} plumbers={plumbers} onStatus={onStatus}/><button className="panel-link" onClick={()=>onNavigate('bookings')}>View all bookings →</button></Panel><Panel title="Quick actions" text="Jump directly to the most common admin tasks."><div className="quick-actions"><button onClick={()=>onNavigate('users')}><span className="quick-action-icon"><Icon name="users" size={15}/></span><span><b>Users</b><span>Manage customer and plumber accounts</span></span>→</button><button onClick={()=>onNavigate('plumbers')}><span className="quick-action-icon"><Icon name="briefcase" size={15}/></span><span><b>Plumbers</b><span>Review and verify professional profiles</span></span>→</button><button onClick={()=>onNavigate('bookings')}><span className="quick-action-icon"><Icon name="bookings" size={15}/></span><span><b>Bookings</b><span>Assign plumbers and update progress</span></span>→</button><button onClick={()=>onNavigate('support')}><span className="quick-action-icon"><Icon name="shield" size={15}/></span><span><b>Support</b><span>Handle reports and contact messages</span></span>→</button></div></Panel></div></>}
function Stat({label,value,icon,tone='primary'}){return <div className="stat-card">{icon&&<span className={`stat-icon tone-${tone}`}><Icon name={icon} size={16}/></span>}<span>{label}</span><strong>{value}</strong></div>}
function BookingTable({bookings,plumbers,onStatus}){return <div className="table-wrap admin-table"><table><thead><tr><th>Customer</th><th>Service</th><th>Date</th><th>Status</th><th>Plumber</th></tr></thead><tbody>{bookings.length?bookings.map(b=><tr key={b.id}><td><div className="customer-booking"><strong>{b.customer_name}</strong><small>{b.customer_email||'No email'}</small></div></td><td>{b.service_name}</td><td>{new Date(b.booking_date).toLocaleDateString()}<small className="subline">{String(b.booking_time).slice(0,5)}</small></td><td><select className="status-select" value={b.status} onChange={e=>onStatus(b.id,e.target.value,b.plumber_id)}>{statuses.map(s=><option key={s} value={s}>{s.replace('_',' ')}</option>)}</select></td><td><select className="assignment-select" value={b.plumber_id||''} onChange={e=>{const id=Number(e.target.value);if(id)onStatus(b.id,'assigned',id)}}><option value="">{b.plumber_name||'Assign plumber'}</option>{plumbers.filter(p=>p.status==='active').map(p=><option key={p.id} value={p.id}>{p.name}{p.verified?' ✓':''}</option>)}</select></td></tr>):<Empty cols={5}/>}</tbody></table></div>}
function PlumberCreate({onCreated}){const [form,setForm]=useState({name:'',email:'',phone:'',password:'',profession:'',location_name:''});const [busy,setBusy]=useState(false);const [error,setError]=useState('');const save=async e=>{e.preventDefault();setBusy(true);setError('');try{await createPlumber(form);setForm({name:'',email:'',phone:'',password:'',profession:'',location_name:''});onCreated()}catch(err){setError(err.message)}finally{setBusy(false)}};return <><form className="admin-form-grid" onSubmit={save}><input placeholder="Full name" value={form.name} onChange={e=>setForm({...form,name:e.target.value})} required/><input type="email" placeholder="Email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})} required/><input placeholder="Phone" value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})}/><input type="password" minLength="6" placeholder="Temporary password" value={form.password} onChange={e=>setForm({...form,password:e.target.value})} required/><input placeholder="Profession" value={form.profession} onChange={e=>setForm({...form,profession:e.target.value})} required/><input placeholder="Service area" value={form.location_name} onChange={e=>setForm({...form,location_name:e.target.value})} required/><button className="primary-action" disabled={busy}>{busy?'Creating…':'Create plumber'}</button></form>{error&&<div className="form-error">{error}</div>}</>}

function ReportResolver({report,onChange}){
 const [status,setStatus]=useState(report.status);const [note,setNote]=useState(report.resolution_note||'');const [open,setOpen]=useState(false);
 const apply=()=>{onChange(report.id,status,note||undefined);setOpen(false)};
 return <div className="report-resolver">
  <select value={status} onChange={e=>{setStatus(e.target.value);setOpen(true)}}><option value="new">New</option><option value="investigating">Investigating</option><option value="resolved">Resolved</option><option value="dismissed">Dismissed</option></select>
  {(open||report.resolution_note)&&<textarea rows="2" placeholder="Resolution note (sent to the reporter)" value={note} onChange={e=>{setNote(e.target.value);setOpen(true)}}/>}
  {open&&<button type="button" className="table-btn" onClick={apply}>Save</button>}
 </div>;
}

function Analytics({data,range,onRangeChange}){
 if(!data)return <div className="empty-state">Loading analytics…</div>;
 const t=data.totals||{};
 const days=[...new Set((data.daily||[]).map(d=>d.day))].sort();
 const byDay=name=>days.map(day=>(data.daily||[]).find(d=>d.day===day&&d.event_name===name)?.total||0);
 const created=byDay('booking_created');const searches=byDay('plumber_search');const maxVal=Math.max(1,...created,...searches);
 return <>
  <div className="section-heading"><div><h2>Product analytics</h2><p>Self-hosted — real events from real use, no third-party service.</p></div><select value={range} onChange={e=>onRangeChange(Number(e.target.value))}><option value="7">Last 7 days</option><option value="30">Last 30 days</option><option value="90">Last 90 days</option></select></div>
  <div className="stat-grid"><Stat label="Searches" value={t.searches||0}/><Stat label="Bookings created" value={t.bookings_created||0}/><Stat label="Bookings completed" value={t.bookings_completed||0}/><Stat label="New accounts" value={t.registrations||0}/><Stat label="Reviews left" value={t.reviews||0}/></div>
  <div className="overview-grid">
   <Panel title="Conversion" text="What share of activity moves to the next stage of the funnel.">
    <div className="conversion-rows">
     <div><span>Search → booking</span><strong>{data.conversion?.search_to_booking!=null?`${data.conversion.search_to_booking}%`:'—'}</strong></div>
     <div><span>Booking → completed</span><strong>{data.conversion?.booking_to_completed!=null?`${data.conversion.booking_to_completed}%`:'—'}</strong></div>
    </div>
   </Panel>
   <Panel title="Daily activity" text="Searches and new bookings per day.">
    {days.length===0?<div className="empty-state">Not enough data yet for a trend.</div>:
     <div className="mini-chart">{days.map((day,i)=>{const bH=Math.round((searches[i]/maxVal)*10)*10;const cH=Math.round((created[i]/maxVal)*10)*10;return <div key={day} className="mini-chart-col" title={`${day}: ${created[i]} bookings, ${searches[i]} searches`}>
       <div className={`mini-bar mini-bar-search bar-h-${bH}`}></div>
       <div className={`mini-bar mini-bar-booking bar-h-${cH}`}></div>
     </div>;})}</div>}
    <div className="mini-chart-legend"><span><i className="dot-primary"/> Bookings</span><span><i className="dot-accent"/> Searches</span></div>
   </Panel>
  </div>
 </>;
}
export default AdminDashboard;
