import React, { useEffect, useState } from 'react';
import '../styles/CustomerDashboard.css';
import Icon from '../components/Icon';
import { useAuth } from '../context/AuthContext';
import { getPlumberBookings, updatePlumberBooking } from '../api/bookingApi';
import { getMyPlumberProfile, updateMyPlumberProfile } from '../api/plumberApi';
import { useAutoRefresh } from '../hooks/useAutoRefresh';

function PlumberDashboard() {
  const { user } = useAuth();
  const [bookings,setBookings]=useState([]); const [profile,setProfile]=useState(null); const [loading,setLoading]=useState(true); const [saving,setSaving]=useState(false); const [error,setError]=useState(''); const [message,setMessage]=useState('');
  const loadBookings=(opts={})=>getPlumberBookings().then(b=>setBookings(b.bookings||[])).catch(e=>{if(!opts.silent)setError(e.message)});
  const load=async()=>{setLoading(true);setError('');try{const [b,p]=await Promise.all([getPlumberBookings(),getMyPlumberProfile()]);setBookings(b.bookings||[]);setProfile(p.profile);}catch(e){setError(e.message)}finally{setLoading(false)}};
  useEffect(()=>{load()},[]);
  // Only bookings are polled in the background — the profile form is left alone while the plumber may be mid-edit.
  useAutoRefresh(()=>loadBookings({silent:true}));
  const update=async(id,status)=>{setError('');try{await updatePlumberBooking(id,status);load()}catch(e){setError(e.message)}};
  const saveProfile=async e=>{e.preventDefault();setSaving(true);setError('');setMessage('');try{const data=await updateMyPlumberProfile(profile);setProfile(data.profile);setMessage('Profile updated. Verification status is controlled by the admin team.')}catch(e){setError(e.message)}finally{setSaving(false)}};
  const active=bookings.filter(b=>['confirmed','on_the_way','arrived','in_progress','assigned'].includes(b.status)).length; const completed=bookings.filter(b=>b.status==='completed'||b.status==='reviewed').length;
  return <div className="dashboard-shell customer-dashboard plumber-dashboard"><div className="dashboard-header"><div><span className="eyebrow">PLUMBER WORKSPACE</span><h1>Welcome, {user?.name?.split(' ')[0]}</h1><p>Manage your profile, availability and assigned jobs.</p></div><span className={`verification-pill ${profile?.verified?'verified':'pending'}`}>{profile?.verified&&<Icon name="check" size={13}/>}{profile?.verified?'Verified profile':'Pending verification'}</span></div>
    {error&&<div className="form-error">{error}</div>}{message&&<div className="form-success">{message}</div>}
    <div className="dashboard-cards"><div className="dashboard-card"><span>Assigned jobs</span><strong>{bookings.length}</strong></div><div className="dashboard-card"><span>Active jobs</span><strong>{active}</strong></div><div className="dashboard-card"><span>Completed</span><strong>{completed}</strong></div><div className="dashboard-card"><span>Rating</span><strong>{Number(profile?.rating||0).toFixed(1)} <small><Icon name="star" size={14} filled/></small></strong></div></div>
    <section className="profile-editor booking-history"><div className="section-heading"><div><h2>Professional profile</h2><p>Keep your public service information accurate. Verified status is managed by an administrator.</p></div></div>{profile&&<form onSubmit={saveProfile} className="profile-form"><div className="profile-grid"><label>Profession<input value={profile.profession||''} onChange={e=>setProfile({...profile,profession:e.target.value})} required/></label><label>Education / training<input value={profile.education||''} onChange={e=>setProfile({...profile,education:e.target.value})}/></label><label>Experience (years)<input type="number" min="0" step="0.5" value={profile.experience_years||0} onChange={e=>setProfile({...profile,experience_years:e.target.value})}/></label><label>Work model<select value={profile.work_mode||'solo'} onChange={e=>setProfile({...profile,work_mode:e.target.value})}><option value="solo">Solo</option><option value="team">Team</option></select></label><label>Service area<input value={profile.location_name||''} onChange={e=>setProfile({...profile,location_name:e.target.value})} required/></label><label>Service radius<select value={profile.service_radius_km||15} onChange={e=>setProfile({...profile,service_radius_km:e.target.value})}><option value="10">10 km</option><option value="15">15 km</option><option value="25">25 km</option><option value="50">50 km</option></select></label></div><label>Professional bio<textarea rows="3" value={profile.bio||''} onChange={e=>setProfile({...profile,bio:e.target.value})}/></label><div className="profile-options"><label><input type="checkbox" checked={!!profile.available} onChange={e=>setProfile({...profile,available:e.target.checked})}/> I am currently available</label><label><input type="checkbox" checked={!!profile.can_travel} onChange={e=>setProfile({...profile,can_travel:e.target.checked})}/> I can travel to nearby areas</label></div><button className="dashboard-action" disabled={saving}>{saving?'Saving…':'Save profile'}</button></form>}</section>
    <section className="booking-history"><div className="section-heading"><div><h2>Assigned jobs</h2><p>Only bookings assigned to your plumber account are shown here.</p></div><button onClick={()=>load()}><Icon name="refresh" size={13}/> Refresh</button></div>{loading?<div className="empty-state">Loading jobs…</div>:bookings.length===0?<div className="empty-state">No jobs have been assigned to you yet.</div>:<div className="table-wrap"><table><thead><tr><th>Customer</th><th>Service</th><th>Date</th><th>Address</th><th>Status</th><th>Actions</th></tr></thead><tbody>{bookings.map(b=><tr key={b.id}><td><strong>{b.customer_name}</strong><small className="time-line">{b.customer_email}</small></td><td>{b.service_name}</td><td>{new Date(b.booking_date).toLocaleDateString()}</td><td>{b.address}</td><td><span className={`status status-${b.status}`}>{b.status.replace('_',' ')}</span></td><td>{b.status==='assigned'&&<button className="table-btn" onClick={()=>update(b.id,'confirmed')}>Accept</button>}{b.status==='confirmed'&&<button className="table-btn" onClick={()=>update(b.id,'on_the_way')}>On the way</button>}{b.status==='on_the_way'&&<button className="table-btn" onClick={()=>update(b.id,'arrived')}>Arrived</button>}{b.status==='arrived'&&<button className="table-btn" onClick={()=>update(b.id,'in_progress')}>Start job</button>}{b.status==='in_progress'&&<button className="table-btn" onClick={()=>update(b.id,'completed')}>Mark complete</button>}{b.status==='assigned'&&<button className="table-btn danger" onClick={()=>update(b.id,'rejected')}>Reject</button>}{['confirmed','on_the_way','arrived'].includes(b.status)&&<button className="table-btn danger" onClick={()=>update(b.id,'cancelled')}>Cancel</button>}</td></tr>)}</tbody></table></div>}</section>
  </div>;
}
export default PlumberDashboard;
